[project]
name = "session_one"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies=[
    "jupyterlab >= 4.2.4",
    "langchain >= 0.2.10",
    "langchain-openai >= 0.1.17",
    "python-dotenv >= 1.0.1",
    "langchain-groq>=0.1.6",
]
